spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TiendaERP;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=123456


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jackson.serialization.fail-on-empty-beans=false

# Configuración de Spring AI (Reemplaza con tu clave real)
spring.ai.googlegenai.api-key=AIzaSyCDOk9Jetou83fJYRhXDj3VthDBUeRYH0E
spring.ai.googlegenai.chat.options.model=gemini-1.5-flash